#!/bin/bash

prog_name="$0"

macaroon=admin
lnd_network=mainnet
protocol=""
while [ $# -gt 0 ];
do
	case "$1" in
		--help)
			echo "Usage: $prog_name --grpc|--rest [--network mainnet|regtest] [--macaroon admin|invoice|readonly]"
			echo '--rest needs to be used for Zeus and iOS version of Zap'
			echo '--grpc for everything else'
			exit 0
			;;
		--network)
			lnd_network="$2"
			shift
			;;
		--macaroon)
			macaroon="$2"
			shift
			;;
		--grpc)
			if [ "$protocol" = "rest" ];
			then
				echo 'You must specify either --grpc or --rest, not both!' >&2
				exit 1
			fi
			protocol="grpc"
			;;
		--rest)
			if [ "$protocol" = "grpc" ];
			then
				echo 'You must specify either --grpc or --rest, not both!' >&2
				exit 1
			fi
			protocol="rest"
			;;
	esac
	shift
done

. /usr/share/lnd/lib/bash.sh || exit 1

case "$protocol" in
	grpc)
		port="$lnd_grpc_port"
		;;
	rest)
		port="$lnd_rest_port"
		;;
	*)
		echo 'Specifying either --grpc or --rest is mandatory' >&2
		echo '--rest needs to be used for Zeus and iOS version of Zap' >&2
		echo '--grpc for everything else' >&2
		exit 1
		;;
esac

case "$macaroon" in
	admin)
		macaroon_file="$lnd_admin_macaroon_file"
		;;
	invoice)
		macaroon_file="$lnd_invoice_macaroon_file"
		;;
	readonly)
		macaroon_file="$lnd_readonly_macaroon_file"
		;;
	*)
		echo "Unknown macaroon: $macaroon" >&2
		exit 1
esac

domain="`cat /var/lib/tor/lndconnect_hidden_service/hostname`"

echo "lndconnect://$domain:$port?cert=`grep -v 'CERTIFICATE' "$lnd_cert_file" | tr -d '=' | tr '/+' '_-'`"'&macaroon='"`base64 "$macaroon_file" | tr -d '=' | tr '/+' '_-'`" | tr -d '\n'
