NBXPLORER_VERSION=2.1.8
NBXPLORER_BUILD_DIR=$(BUILD_DIR)/nbxplorer-$(NBXPLORER_VERSION)


NBXPLORER_SOURCE_DIR=$(SOURCE_DIR)/nbxplorer
NBXPLORER_DEB_VERSION=$(NBXPLORER_VERSION)-1
NBXPLORER_BIN_VERSION=$(NBXPLORER_DEB_VERSION)_$(DEB_ARCH)
NBXPLORER_SHARE_VERSION=$(NBXPLORER_DEB_VERSION)_all

NBXPLORER_BIN_PACKAGES=$(addsuffix _$(NBXPLORER_BIN_VERSION), nbxplorer)
NBXPLORER_SHARE_PACKAGES=$(addsuffix _$(NBXPLORER_SHARE_VERSION), nbxplorer-mainnet)
NBXPLORER_PACKAGES=$(addprefix $(BUILD_DIR)/, $(addsuffix .deb, $(NBXPLORER_BIN_PACKAGES) $(NBXPLORER_SHARE_PACKAGES)))
NBXPLORER_EXTRA_FILES=$(addprefix $(BUILD_DIR)/,nbxplorer_$(NBXPLORER_BIN_VERSION).buildinfo nbxplorer_$(NBXPLORER_BIN_VERSION).changes nbxplorer_$(NBXPLORER_DEB_VERSION).dsc nbxplorer_$(NBXPLORER_DEB_VERSION).tar.gz)
