#!/bin/bash

cookie_dir="/var/run/thunderhub-system-$BITCOIN_NETWORK/sso"
mkdir -p "$cookie_dir" || exit 1
chgrp "thunderhub-system-$BITCOIN_NETWORK-sso" "$cookie_dir" || exit 1
chmod 750 "$cookie_dir" || exit 1
# thunderhub is unable to create the cookie until someone accesses it, which is impossible without cookie...
head -c 64 /dev/urandom | xxd -p -c 128 > "$cookie_dir/cookie.tmp" || exit 1
mv "$cookie_dir/cookie.tmp" "$cookie_dir/cookie"

cd /usr/lib/thunderhub || exit 1
exec ./node_modules/next/dist/bin/next start -- -p "$BIND_PORT"
exit $?
