#!/bin/bash

find_arg() {
	local arg="$1"
	local var="$2"
	shift 2

	while [ $# -gt 0 ];
	do
		if [ "$1" = "--$arg" ];
		then
			test -n "$var" && declare -g "$var=$2"
			return 0
		fi
		shift
	done
	return 1
}

doesnt_need_macaroon() {
	while [ $# -gt 0 ];
	do
		if echo "$1" | grep -q '^--';
		then
			shift
		else
			test "$1" = "create" || test "$1" = "unlock"
			return $?
		fi
	done
	return 1
}

lncli=/usr/lib/lncli/lncli
lnd_network=mainnet
find_arg "network" "lnd_network" "$@"

. /usr/share/lnd/lib/bash.sh

# Don't mess with command line if any of the arguments is present
if find_arg tlscertpath "" "$@" || find_arg macaroonpath "" "$@" || find_arg rpcserver "" "$@";
then
	exec "$lncli" "$@"
	exit $?
else
	if [ -n "$lnd_max_macaroon_file" ];
	then
		exec "$lncli" --tlscertpath "$lnd_cert_file" --macaroonpath "$lnd_max_macaroon_file" --rpcserver "localhost:$lnd_grpc_port" "$@"
		exit $?
	else
		if doesnt_need_macaroon "$@";
		then
			exec "$lncli" --tlscertpath "$lnd_cert_file" --rpcserver "localhost:$lnd_grpc_port" "$@"
			exit $?
		else
			echo "You don't have the permissions to access LND macaroons or the wallet is not initialized" >&2
			echo "Consider runnig with sudo installing the package lnd-auto-unlock, or manually initializing the wallet" >&2
			echo >&2
			echo "Note: access attempted to these macaroons:" >&2
			echo "$lnd_admin_macaroon_file" >&2
			echo "$lnd_invoice_macaroon_file" >&2
			echo "$lnd_readonly_macaroon_file" >&2
			exit 1
		fi
	fi
fi
