#!/bin/bash

function find_arg() {
	local arg="$1"
	local var="$2"
	shift 2

	while [ $# -gt 0 ];
	do
		if [ "$1" = "--$arg" ];
		then
			test -n "$var" declare -g "$var=$2"
			return 1
		fi
		shift
	done
	return 0
}

lncli=/usr/lib/lncli/lncli
lnd_network=mainnet
find_arg "network" "lnd_network" "$@"

# This is currently the same, but we're future-proofing if we need to do some mapping
internal_network="$lnd_network"

tlscert_path="/var/lib/lnd-system-$internal_network/public/tls.cert"
admin_macaroonpath="/var/lib/lnd-system-$internal_network/private/admin.macaroon"
invoice_macaroonpath="/var/lib/lnd-system-$internal_network/invoice/invoice.macaroon"
readonly_macaroonpath="/var/lib/lnd-system-$internal_network/readonly/readonly.macaroon"

extra_flags=""

if [ '!' -r "$tlscert_path" ];
then
	tlscert_path=""
fi

if find_arg tlscertpath "" "$@";
then
	extra_flags="$extra_flags --tlscertpath $tlscert_path"
fi

if find_arg macaroonpath "" "$@";
then
	if [ -r "$admin_macaroonpath" ];
	then
		macaroon_path="$admin_macaroonpath"
	else
		if [ -r "$invoice_macaroonpath" ];
		then
			macaroon_path="$invoice_macaroonpath"
		else
			macaroon_path="$readonly_macaroonpath"
		fi
	fi
	extra_flags="$extra_flags --macaroonpath $macaroon_path"
fi

if find_arg rpcserver "" "$@";
then
	grpc_port="`grep '^rpclisten=' "/etc/lnd-system-$internal_network/lnd.conf" | sed 's/^.*://'`"
	extra_flags="$extra_flags --rpcserver localhost:$grpc_port"
fi

exec "$lncli" $extra_flags "$@"
exit $?
