BITCOIN_VERSION=0.18.1
LAANWJ_FPRINT=01EA5486DE18A882D4C2684590C8019E36C2E964
BUILD_STRATEGY=fetch_binary

BITCOIN_DEB_VERSION=$(BITCOIN_VERSION)-1
BITCOIN_BIN_VERSION=$(BITCOIN_DEB_VERSION)_$(DEB_ARCH)
BITCOIN_SHARE_VERSION=$(BITCOIN_DEB_VERSION)_all

BITCOIN_BIN_PACKAGES=$(addsuffix _$(BITCOIN_BIN_VERSION), bitcoind)
BITCOIN_SHARE_PACKAGES=$(addsuffix _$(BITCOIN_SHARE_VERSION), bitcoin-mainnet bitcoin-mainnet-fullchain bitcoin-mainnet-txindex bitcoin-mainnet-zmq)
BITCOIN_PACKAGES=$(addprefix $(BUILD_DIR)/, $(addsuffix .deb, $(BITCOIN_BIN_PACKAGES) $(BITCOIN_SHARE_PACKAGES)))
# Imperfect but should work in most scenarios
#BITCOIN_CONTROL_FILES_SRC:=$(wildcard $(BITCOIN_SOURCE_DIR)assets/debian/*)
#BITCOIN_CONTROL_FILES_DST:=$(subst $(BITCOIN_SOURCE_DIR)assets/,bitcoin-$(BITCOIN_VERSION)/,$(BITCOIN_CONTROL_FILES_SRC))
#BITCOIN_CONFIG_FILES_SRC:=$(wildcard $(BITCOIN_SOURCE_DIR)assets/config/*)
#BITCOIN_CONFIG_FILES_DST:=$(subst $(BITCOIN_SOURCE_DIR)assets/config/,bitcoin-$(BITCOIN_VERSION)/config/,$(BITCOIN_CONFIG_FILES_SRC))
BITCOIN_EXTRA_FILES=$(addprefix $(BUILD_DIR)/,bitcoin_$(BITCOIN_BIN_VERSION).buildinfo bitcoin_$(BITCOIN_BIN_VERSION).changes bitcoin_$(BITCOIN_DEB_VERSION).dsc bitcoin_$(BITCOIN_DEB_VERSION).tar.gz)
