#!/bin/bash

function scan_args() {
	local prog="$0";
	network="`echo "$prog" | sed 's/^.*-//g'`"
	case "$network" in 
		mainnet|regtest)
			;;
		testnet|signet|simnet)
			echo "Network supported by Electrum but $network unsupported by CADR" >&2
			echo "Use electrum directly, not this launcher" >&2
			exit 1
			;;
		*)
			echo "Unrecognized network $1. Launch the binary using a symlink."
			exit 1
			;;
	esac
	while [ $# -gt 0 ];
	do
		case "$1" in
			--testnet|--regtest|--signet|--simnet)
				echo "Network is implied by the binary name, don't use an argument" >&2
				exit 1
				;;
			-h|--help)
				echo "Launcher for electrum with a self-hosted server"
				echo ""
				echo "Usage: $prog [daemon|gui] [URLS...]"
				echo ""
				echo "This launcher supplies its own --oneserver and --server arguments to electrum. These are currently read from /etc/electrs-{network}/conf.d/interface.toml but this will change in the future."
				echo "Note that for --offline or RPC use electrum binary directly. This launcher is only intended for GUI or daemon"
				;;
			daemon)
				if [ "$is_daemon" = 1 ] || [ "$is_gui" = 1 ];
				then
					echo "Either daemon or gui have to be specified and at most once" >&2
					exit 1
				fi
				is_daemon=1
				;;
			gui)
				if [ "$is_daemon" = 1 ] || [ "$is_gui" = 1 ];
				then
					echo "Either daemon or gui have to be specified and at most once" >&2
					exit 1
				fi
				is_gui=1
				;;
			--server)
				echo "Error: --server would make this launcher pointless, use the electrum binary instead." >&2
				exit 1
				;;
			--oneserver)
				echo "Warning: --oneserver is already the default" >&2
				;;
			bitcoin:*)
				break
				;;
			lightning:*)
				break
				;;
			--)
				break
				;;
		esac
		shift
	done
}

scan_args "$@"

first_arg=""
if [ "$is_daemon" = 1 ];
then
	cmd="daemon"
	shift
elif [ "$is_gui" = 1 ];
then
	cmd="gui"
	shift
fi

if [ "$network" = regtest ];
then
	network_arg="--regtest"
fi

SERVER="`grep '^electrum_rpc_addr' "/etc/electrs-$network/conf.d/interface.toml" | sed -e 's/^electrum_rpc_addr *= *"//' -e 's/"$//'`:t" || exit 1

# Skipmerklecheck is safe because we connect to our own local server
# Currently this is hardcoded to electrs, but should use /etc/electrum-server/interface
# or something similar with update-alternatives. This needs implementation of interface
# feature in debcrafter (see #2).
exec electrum $network_arg $cmd --oneserver --skipmerklecheck --server "$SERVER" "$@"
